spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/p1296_saas_test
    username: p1296_saas_test
    password: Wr.b7lWlvF=AzI413lSlpek7_7C]of
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
