spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/p1296_saas_test
    username: p1296_saas_test
    password: Wr.b7lWlvF=AzI413lSlpek7_7C]of
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: mail63.mydevil.net
    port: 587
    username: no-reply@devcolibri.pl
    password: 5eveTo51MlMgKUzQ-pCNS14
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
